stages:
- test

pre_commit:
  stage: test
  image: python:$PY-alpine
  parallel:
    matrix:
    - PY: ["3.9", "3.10", "3.11", "3.12"]
  script:
  - apk add git
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pre-commit
  - pre-commit run -a

tox:
  stage: test
  image: alpine
  script:
  - apk add git py3-btrfs-progs btrfs-progs py3-tox
  - tox -e gitlab
