repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: '.*\.golden$'
  - id: mixed-line-ending
  - id: name-tests-test
  - id: trailing-whitespace
    exclude: '.*\.golden$'
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 2.1.3
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/google/yamlfmt
  rev: v0.12.1
  hooks:
  - id: yamlfmt
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    additional_dependencies: [types-all, arrow>=1, "boto3-stubs[boto3,s3]", "moto[s3]", pytest, rich, typing_extensions>=4.4]
    args: []
