[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=64",
  "setuptools_scm>=8",
]

[project]
name = "btrfs2s3"
description = "Snapshot btrfs volumes and back them up to s3"
authors = [
  {name = "Steven Brudenell", email = "steven.brudenell@gmail.com"}
]
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dynamic = [
  "version",
]
dependencies = [
  "arrow>=1",
  "boto3[crt]",
  "typing_extensions>=4.4",
]
[project.scripts]
btrfs2s3 = "btrfs2s3.main:main"

[tool.setuptools_scm]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = [
  "ANN101",
  "ANN102",
  "ISC001",
  "COM812",
]
select = ["ALL"]

[tool.ruff.lint.isort]
force-single-line = true
force-sort-within-sections = true
order-by-type = false

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "D",
  "PLR",
  "S",
  "SLF",
]
"src/btrfs2s3/_internal/*" = [
  "PLR",
]
"src/btrfs2s3/resolver.py" = [
  "D",
]
"src/btrfs2s3/assessor.py" = [
  "D",
]
"src/btrfs2s3/commands/*" = [
  "T",
]
"typeshed/*" = [
  "A",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
mypy_path = "typeshed"
strict = true
